In [232]:
import pandas as pd 
import numpy as np

In [233]:
State = ['CA', 'DC', 'NY', 'VA', 'WA', 'TX', 'MA','IL','ML','PA','NC','GA','CO','NJ','FL']
Av_Salary = [90.5, 73, 71.5, 71, 117.3, 68, 70.5, 65.3 , 67.3, 64, 67.3,65, 67, 67.3, 67.3]
population = [39.5, .633, 8.6, 8.5, 2.6, 28.7,6.9,12.7, 6.04, 12.8,10.4,10.5, 5.6,8.9,21.3]
Jobs = [3521, 1683, 1322, 1243, 1075, 877, 824, 659, 509, 455, 428, 321, 313, 313, 302]
CPI = [151.7,158.4,139.1,100.7, 110.7, 91.5, 131.6, 94.5, 129.7, 101.7, 94.9, 89.2, 105.6, 125.1, 97.9]
Weather = [10, 7.5, 1, 7, 1, 10, 3, 2, 1, 5, 9, 9, 7, 2, 9]
People = [5, 5, 2, 4, 7, 8, 9, 1, 5, 3, 8, 7.5, 8, 1, 4]

In [234]:
df = pd.DataFrame(index=State)

In [235]:
df['JobsPerCapita'] = np.array(Jobs)/np.array(population)
df['Weather'] = Weather
df['People'] = People
df['S/CPI'] = np.array(Av_Salary)/np.array(CPI)
df

    JobsPerCapita  Weather  People     S/CPI
CA      89.139241     10.0     5.0  0.596572
DC    2658.767773      7.5     5.0  0.460859
NY     153.720930      1.0     2.0  0.514019
VA     146.235294      7.0     4.0  0.705065
WA     413.461538      1.0     7.0  1.059621
TX      30.557491     10.0     8.0  0.743169
MA     119.420290      3.0     9.0  0.535714
IL      51.889764      2.0     1.0  0.691005
ML      84.271523      1.0     5.0  0.518890
PA      35.546875      5.0     3.0  0.629302
NC      41.153846      9.0     8.0  0.709168
GA      30.571429      9.0     7.5  0.728700
CO      55.892857      7.0     8.0  0.634470
NJ      35.168539      2.0     1.0  0.537970
FL      14.178404      9.0     4.0  0.687436

In [236]:
def standardize(array): 
    mean = np.mean(array)
    stdev = np.std(array)
    new = []
    
    for i in array:
        x = (i-mean)/stdev
        new.append(x)
    
    return np.array(new)

def min_max(array):
    mini = np.min(array)
    maxi = np.max(array)
    new = []
    
    for i in array:
        x = (i-mini)/(maxi-mini)
        new.append(x)
    
    return np.array(new)

In [237]:
for i in df.columns: 
    df[i] = min_max(df[i])
    
df

    JobsPerCapita   Weather  People     S/CPI
CA       0.028345  1.000000  0.5000  0.226657
DC       1.000000  0.722222  0.5000  0.000000
NY       0.052765  0.000000  0.1250  0.088783
VA       0.049935  0.666667  0.3750  0.407851
WA       0.150981  0.000000  0.7500  1.000000
TX       0.006193  1.000000  0.8750  0.471491
MA       0.039795  0.222222  1.0000  0.125017
IL       0.014260  0.111111  0.0000  0.384371
ML       0.026504  0.000000  0.5000  0.096919
PA       0.008080  0.444444  0.2500  0.281319
NC       0.010200  0.888889  0.8750  0.414704
GA       0.006199  0.888889  0.8125  0.447325
CO       0.015774  0.666667  0.8750  0.289950
NJ       0.007937  0.111111  0.0000  0.128784
FL       0.000000  0.888889  0.3750  0.378410

In [238]:
df['Weightless'] = df.JobsPerCapita + df.Weather + df.People + df['S/CPI']

In [239]:
df.sort_values('Weightless', ascending=False)

    JobsPerCapita   Weather  People     S/CPI  Weightless
TX       0.006193  1.000000  0.8750  0.471491    2.352684
DC       1.000000  0.722222  0.5000  0.000000    2.222222
NC       0.010200  0.888889  0.8750  0.414704    2.188793
GA       0.006199  0.888889  0.8125  0.447325    2.154912
WA       0.150981  0.000000  0.7500  1.000000    1.900981
CO       0.015774  0.666667  0.8750  0.289950    1.847390
CA       0.028345  1.000000  0.5000  0.226657    1.755002
FL       0.000000  0.888889  0.3750  0.378410    1.642299
VA       0.049935  0.666667  0.3750  0.407851    1.499453
MA       0.039795  0.222222  1.0000  0.125017    1.387035
PA       0.008080  0.444444  0.2500  0.281319    0.983844
ML       0.026504  0.000000  0.5000  0.096919    0.623423
IL       0.014260  0.111111  0.0000  0.384371    0.509742
NY       0.052765  0.000000  0.1250  0.088783    0.266549
NJ       0.007937  0.111111  0.0000  0.128784    0.247832

In [240]:
w_df = pd.DataFrame(index = State)

In [243]:
def weighting(options, weather, people, ratio): 
    w_df['JobsPerCapita'] = df.JobsPerCapita*options
    w_df['Weather'] = df.Weather*weather
    w_df['People'] = df.People*people
    w_df['Iratio'] = df['S/CPI']*ratio
    w_df['Weight'] = w_df.JobsPerCapita + w_df.Weather + w_df.People + w_df.Iratio
    
    return w_df.sort_values('Weight', ascending=False)

In [254]:
#1. Job Option weight
#2. Weather weight
#3. People weight
#4. Income to Cost of living Weight
weighting(6, 7.5, 7, 10)

    JobsPerCapita   Weather  People     Iratio     Weight
TX       0.037161  7.500000  6.1250   4.714909  18.377069
NC       0.061201  6.666667  6.1250   4.147039  16.999907
GA       0.037192  6.666667  5.6875   4.473246  16.864605
WA       0.905887  0.000000  5.2500  10.000000  16.155887
DC       6.000000  5.416667  3.5000   0.000000  14.916667
CO       0.094641  5.000000  6.1250   2.899501  14.119142
CA       0.170070  7.500000  3.5000   2.266570  13.436640
FL       0.000000  6.666667  2.6250   3.784101  13.075767
VA       0.299608  5.000000  2.6250   4.078515  12.003123
MA       0.238771  1.666667  7.0000   1.250175  10.155612
PA       0.048480  3.333333  1.7500   2.813193   7.945006
IL       0.085559  0.833333  0.0000   3.843709   4.762601
ML       0.159026  0.000000  3.5000   0.969186   4.628212
NJ       0.047622  0.833333  0.0000   1.287841   2.168797
NY       0.316592  0.000000  0.8750   0.887834   2.079425