In [38]:
import os 
import pandas as pd 
import numpy as np 
import seaborn as sb

In [3]:
df = pd.read_csv('GSAF5.csv', delimiter=',', encoding="ISO-8859-1")

In [4]:
df.shape

(5992, 24)

In [5]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [6]:
df.dtypes

Case Number               object
Date                      object
Year                       int64
Type                      object
Country                   object
Area                      object
Location                  object
Activity                  object
Name                      object
Sex                       object
Age                       object
Injury                    object
Fatal (Y/N)               object
Time                      object
Species                   object
Investigator or Source    object
pdf                       object
href formula              object
href                      object
Case Number.1             object
Case Number.2             object
original order             int64
Unnamed: 22               object
Unnamed: 23               object
dtype: object

In [7]:
df.isnull().sum()

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

In [62]:
df = df.drop(columns=['Unnamed: 22', 'Unnamed: 23','href', 'href formula', 'pdf',
                 'Case Number.1','Case Number.2','Investigator or Source', 'original order','Name'])

KeyError: "['Unnamed: 22' 'Unnamed: 23' 'href' 'href formula' 'pdf' 'Case Number.1'\n 'Case Number.2' 'Investigator or Source' 'original order'] not found in axis"

In [9]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark

In [10]:
a = df['Time']

In [11]:
count = 0 


for i in a: 
    try:
        if 3< len(i) <=5: 
            b= i.split('h') 
            c= int(b[0]) + int(b[1])/60
            df['Time'][count] = c
    except: 
        pass 
    count+=1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [35]:
df.head(100)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10.7167,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,60s,Minor injury to arm,N,15.25,3' to 4' shark
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14.5,"Tiger shark, 10?"
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,50,FATAL,Y,15.6667,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,NaN,NaN
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,NaN,"No inury, board broken in half by shark",N,NaN,NaN
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,9,Foot bitten,N,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15,"Bull shark, 6'"
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,37,Minor injury to ankle,N,14,NaN
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17,"Bull shark, 3.5 m"
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,49,Minor injury to ankle,N,16,NaN
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'"
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,40,Lacerations to right hand,N,11.5,Blue shark
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,72,Lacerations to leg,N,NaN,NaN
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,NaN,"No injury, shark nudged kayak repeatedly",N,NaN,White shark
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,43,Laceration to left forearm PROVOKED INCIDENT,N,NaN,"Nurse shark, 4'"
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12,NaN
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,29,Lacerations to left leg,N,19.0833,NaN
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,NaN,Lacerations to face and right leg,N,NaN,"Bull shark, 6'"
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,31,Laceration to left calf from hooked shark PROV...,N,NaN,"reef shark, 1m"
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,NaN,"No injury, shark bit trolling motor",N,NaN,"Tiger shark, 10'"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2016.04.18,18-Apr-16,2016,Provoked,FRENCH POLYNESIA,Tuamotos,Makemo Atoll,Spearfishing,Teva Tokoragi,M,26,"Severe lacerations to right forearm, hand and ...",N,NaN,"Grey reef shark, 2 m"
71,2016.04.13,13-Apr-16,2016,Unprovoked,USA,Florida,"Off Singer Island, Palm Beach County",Spearfishing,Kyle Senkowicz,M,26,Multiple bites to right arm,N,NaN,"Bull shark, 7'"
72,2016.04.09,09-Apr-16,2016,Unprovoked,NEW CALEDONIA,Grand Terre,Poe Beach,Walking,Nicole Malignon,F,69,FATAL,Y,10.75,"Tiger shark, 2.5 m"
73,2016.04.08,08-Apr-16,2016,Invalid,CAPE VERDE,Boa Vista Island,NaN,NaN,a British citizen,M,60,"""Serious""",N,NaN,Shark involvement not confirmed
74,2016.04.07.b,07-Apr-16,2016,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Fishing,Jonathan Lester,M,34,Left hand bitten,N,NaN,5' to 6' shark
75,2016.04.07.a,07-Apr-16,2016,Invalid,USA,Florida,"Corners Beach, Jupiter, Palm Beach County",SUP,Maximo Trinidad,M,NaN,Fell off board when spinner shark leapt from t...,N,NaN,NaN
76,2016.03.31,31-Mar-16,2016,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,J. Orr,F,46,Minor injury to left foot,N,11,NaN
77,2016.03.30,30-Mar-16,2016,Unprovoked,AUSTRALIA,New South Wales,Bombo Beach,Surfing,Brett Connellan,M,22,Severe injury to thigh,N,19,NaN
78,2016.03.28.b,28-Mar-16,2016,Unprovoked,USA,Florida,"Fort Myers Beach, Lee County",NaN,Nick Kawa,M,Teen,Minor injury to arm. Possibly caused by smalll...,N,NaN,Shark involvement not confirmed
79,2016.03.28.a,28-Mar-16,2016,Unprovoked,AUSTRALIA,New South Wales,North Cronulla Beach,Surfing,Roie Smyth,M,41,"No injury, board dented",N,11,NaN
80,2016.03.26,26-Mar-16,2016,Provoked,BAHAMAS,NaN,NaN,NaN,Henry Kreckman,M,9,Minor injury to chest PROVOKED INCIDENT,N,NaN,"Nurse shark, 2.5-ft"
81,2016.03.13,13-Mar-16,2016,Invalid,USA,California,"Bolsa Chica State Park, Orange County",Surfing,unknown,NaN,NaN,Board reportedly bumped by shark. No injury,N,NaN,Shark involvement not confirmed
82,2016.03.11,11-Mar-16,2016,Unprovoked,USA,Florida,"Vero Beach, St. Lucie County",Body surfing,Daniel Kenny,M,19,Lacerations to right foot and ankle,N,13.5,NaN
83,2016.03.10,10-Mar-16,2016,Unprovoked,Fiji,Vanua Levu,NaN,Diving for beche-de-mer,Maika Tabua,M,45,FATAL,Y,NaN,NaN
84,2016.03.04,04-Mar-16,2016,Unprovoked,USA,Florida,"Ocean Reef Park, Singer Island, Palm Beach County",NaN,male,M,12,Superficial injury to foot,N,NaN,NaN
85,2016.03.03.R,Reported 03-Mar-2016,2016,Unprovoked,AUSTRALIA,South Australia,Wrights Bay,Fishing,Lee Taplin,M,NaN,Puncture wounds to right calf,N,NaN,Bronze whaler
86,2016.03.02,02-Mar-16,2016,Unprovoked,BRAZIL,Santa Catarina State,Escalerio Beach BalneÃ¡rio CamboriÃº,Swimming,Rafael Hermes Thomas,M,41,Minor injury to head,N,NaN,Sandtiger shark
87,2016.02.22,22-Feb-16,2016,Unprovoked,NEW CALEDONIA,South Province,"Ricaudy Reef, Noumea",Kite surfing,Adrian *,M,21,Puncture wounds to right thigh,N,19,NaN
88,2016.02.19,19-Feb-2016,2016,Unprovoked,NEW CALEDONIA,South Province,Yate,Spearfishing,male,M,31,Forearm bitten,N,16,NaN
89,2016.02.12,12-Feb-16,2016,Unprovoked,DOMINICAN REPUBLIC,Altagracia Province,"Bavaro Beach, Punta Cana",Wading,Patricia Howe,F,NaN,Avulsion injury to lower leg,N,15,NaN
90,2016.02.10.R,Reported 10-Feb-2016,2016,Invalid,CAYMAN ISLANDS,Grand Cayman,Stingray City Bar,Feeding stingrays?,Richard Branson,M,65,Minor injury to wrist from Southern stingray,N,NaN,No shark involvement
91,2016.02.10,10-Feb-16,2016,Invalid,AUSTRALIA,Tasmania,Nettley Bay,Surfing,male,M,NaN,"No injury, knocked off board",N,12.5,No shark involvement
92,2016.02.05,05-Feb-16,2016,Unprovoked,AUSTRALIA,Queensland,Stradbroke Island,Walking,female,F,45,Foot nipped,N,13.3333,NaN
93,2016.02.04,04-Feb-16,2016,Unprovoked,AUSTRALIA,New South Wales,Hams Beach,Windsurfing,Andrew Morris,M,40,"No injury, shark bit board",N,NaN,NaN
94,2016.01.29,29-Jan-16,2016,Boat,SOUTH AFRICA,KwaZulu-Natal,NaN,Kayak fishing,Dev De Lange,M,NaN,"No injury, shark capsized kayak",N,NaN,NaN
95,2016.01.28,28-Jan-16,2016,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai",Surfing,male,M,NaN,Lacerations to both hands,N,14,"Reef shark, 5'"
96,2016.01.25,25-Jan-16,2016,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai,",Surfing,Kaya Waldman,F,15,No injury,N,11.5,NaN
97,2016.01.24.b,24-Jan-16,2016,Unprovoked,USA,Texas,Off Surfside,Spearfishing,Keith Love,M,NaN,"Bruised ribs & tail bone, speargun broken and ...",N,NaN,Bull sharks x 2
98,2016.01.24.a,24-Jan-16,2016,Boat,UNITED ARAB EMIRATES,Fujairah Emirate,35 miles off Fujairah,Fishing,Occupants: Hamza Humaid Al SahraÂ’a & 5 crew,M,NaN,"No injury to occupants, shark leapt into boat",N,NaN,Mako shark
99,2016.01.23,23-Jan-16,2016,Unprovoked,USA,Hawaii,"Wailea Beach, Maui",Paddle boarding,Matt Mason,M,48,No injury,N,NaN,"Tiger shark, 14'"

In [13]:
count1 = 0 


for i in a: 
    try:
        if 'night' in i.lower(): 
            df['Time'][count1] = 22
        if 'morning' in i.lower(): 
            df['Time'][count1] = 9
        if 'after' in i.lower(): 
            df['Time'][count1] = 16
        if 'evening' in i.lower(): 
            df['Time'][count1] = 19
        if isinstance(i, str):
            df['Time'][count1] = float('nan')
            
        
    except: 
        
        pass
    count1+=1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

In [14]:
count1=0
for i in a: 
    try: 
        if isinstance(i, str): 
            count1+=1 
    except: 
        pass 
print(count1)

0

In [15]:
len(df['Time'].unique())

235

In [16]:
df.dtypes

Case Number    object
Date           object
Year            int64
Type           object
Country        object
Area           object
Location       object
Activity       object
Name           object
Sex            object
Age            object
Injury         object
Fatal (Y/N)    object
Time           object
Species        object
dtype: object

In [36]:
df.head(10)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10.7167,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,60s,Minor injury to arm,N,15.25,3' to 4' shark
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14.5,"Tiger shark, 10?"
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,50,FATAL,Y,15.6667,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,NaN,NaN

In [33]:
df['Time'].mean()

13.405846342209971

In [42]:
if 'Sep' in df['Date']: 
    print(0)

In [57]:
count1 = 0 

series = df['Date']

for i in series: 
    try:
        if 'jan' in i.lower(): 
            df['Date'][count1] = 1
        if 'feb' in i.lower(): 
            df['Date'][count1] = 2
        if 'mar' in i.lower(): 
            df['Date'][count1] = 3
        if 'apr' in i.lower(): 
            df['Date'][count1] = 4
        if 'may' in i.lower(): 
            df['Date'][count1] = 5
        if 'jun' in i.lower(): 
            df['Date'][count1] = 6
        if 'jul' in i.lower(): 
            df['Date'][count1] = 7
        if 'aug' in i.lower(): 
            df['Date'][count1] = 8
        if 'sep' in i.lower(): 
            df['Date'][count1] = 9
        if 'oct' in i.lower(): 
            df['Date'][count1] = 10
        if 'nov' in i.lower(): 
            df['Date'][count1] = 11
        if 'dec' in i.lower(): 
            df['Date'][count1] = 12
        else: 
            df['Date'][count1] = float('nan')
            
        
    except: 
        pass
    count1+=1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [58]:
len(series)

5992

In [59]:
len(series.unique())

13

In [61]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2016.09.18.c,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13,NaN
1,2016.09.18.b,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11,NaN
2,2016.09.18.a,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10.7167,NaN
3,2016.09.17,9,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN
4,2016.09.15,9,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark
5,2016.09.15.R,9,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,NaN
6,2016.09.11,9,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,60s,Minor injury to arm,N,15.25,3' to 4' shark
7,2016.09.07,9,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14.5,"Tiger shark, 10?"
8,2016.09.06,9,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,50,FATAL,Y,15.6667,NaN
9,2016.09.05.b,9,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,NaN,NaN
10,2016.09.05.a,9,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,NaN,"No inury, board broken in half by shark",N,NaN,NaN
11,2016.09.04,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,9,Foot bitten,N,NaN,NaN
12,2016.09.01,9,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark
13,2016.08.29.b,8,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15,"Bull shark, 6'"
14,2016.08.29.a,8,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,37,Minor injury to ankle,N,14,NaN
15,2016.08.27,8,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17,"Bull shark, 3.5 m"
16,2016.08.25,8,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,49,Minor injury to ankle,N,16,NaN
17,2016.08.07,8,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN
18,2016.08.06,8,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'"
19,2016.08.04,8,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark
20,2016.07.29,7,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,40,Lacerations to right hand,N,11.5,Blue shark
21,2016.07.28.R,7,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,72,Lacerations to leg,N,NaN,NaN
22,2016.07.28,7,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,NaN,"No injury, shark nudged kayak repeatedly",N,NaN,White shark
23,2016.07.27,7,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,43,Laceration to left forearm PROVOKED INCIDENT,N,NaN,"Nurse shark, 4'"
24,2016.07.26,7,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12,NaN
25,2016.07.24,7,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,29,Lacerations to left leg,N,19.0833,NaN
26,2016.07.23.b,7,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN
27,2016.07.23.a,7,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,NaN,Lacerations to face and right leg,N,NaN,"Bull shark, 6'"
28,2016.07.20,7,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,31,Laceration to left calf from hooked shark PROV...,N,NaN,"reef shark, 1m"
29,2016.07.17,7,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,NaN,"No injury, shark bit trolling motor",N,NaN,"Tiger shark, 10'"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,ND.0031,NaN,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,"Aircraft ditched in the sea, swimming ashore",male,M,NaN,Shark bumped him,N,NaN,NaN
5963,ND.0030,NaN,0,Unprovoked,BURMA,NaN,NaN,Bathing,male,M,NaN,Fatal x 2,Y,NaN,NaN
5964,ND.0028,NaN,0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,NaN,No injury to occupant; shark capsized boat,N,NaN,White shark
5965,ND.0027,NaN,0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,Sponge diving,Psarofa-gomenes,M,NaN,Head bitten,N,NaN,NaN
5966,ND.0026,NaN,0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark
5967,ND.0025,NaN,0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,NaN,NaN,UNKNOWN,NaN,NaN
5968,ND.0024,NaN,0,Unprovoked,REUNION,Saint-Denis,Barachois,Swimming,NaN,NaN,NaN,FATAL,Y,NaN,NaN
5969,ND.0023,NaN,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,Wading,Madelaine Dalton,F,NaN,Ankle bitten,N,NaN,NaN
5970,ND.0022,NaN,0,Unprovoked,AUSTRALIA,NaN,NaN,Pearl diving,Jaringoorli,M,NaN,Lacerations to thigh,N,NaN,NaN
5971,ND.0021,NaN,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Swimming in pool formed by construction of a w...,Indian boy,M,NaN,"FATAL, leg severed",Y,NaN,NaN
5972,ND.0020,NaN,0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,NaN,FATAL,Y,NaN,NaN
5973,ND.0019,NaN,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,James Kelley,M,NaN,2-inch lacerations,N,NaN,NaN
5974,ND.0018,NaN,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,V?ng TÃ u,Swimming around anchored ship,crewman,M,NaN,Foot bitten,N,NaN,NaN
5975,ND.0017,NaN,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,NaN,FATAL,Y,NaN,NaN
5976,ND.0016,NaN,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,NaN,FATAL,Y,NaN,NaN
5977,ND.0015,NaN,0,Unprovoked,FIJI,Moala Island,NaN,Wreck of large double sailing canoe,20 Fijians,NaN,NaN,"FATAL, 18 people were killed by sharks, 2 sur...",Y,NaN,NaN
5978,ND.0014,7,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,NaN,"""Lost leg""",N,NaN,NaN
5979,ND.0013,7,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,a native fisherman,M,NaN,"FATAL, body not recovered but shark was caught...",Y,NaN,NaN
5980,ND.0012,7,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,a young Scotsman,M,NaN,"FATAL, leg stripped of flesh",Y,NaN,NaN
5981,ND.0011,NaN,0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,NaN,Foot severed,N,NaN,NaN
5982,ND.0010,NaN,0,Unprovoked,USA,Hawaii,Puna,NaN,A chiefess,F,NaN,Ankle bitten,N,NaN,NaN
5983,ND.0009,NaN,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,NaN,"FATAL, knocked overboard by tail of shark & ca...",Y,NaN,Blue pointer
5984,ND.0008,NaN,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,NaN,FATAL,Y,NaN,Blue pointer
5985,ND.0007,NaN,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,NaN,FATAL,Y,NaN,Blue pointers
5986,ND.0006,NaN,0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,NaN,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...
5987,ND.0005,NaN,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN
5988,ND.0004,NaN,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN
5989,ND.0003,NaN,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN
5990,ND.0002,NaN,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN
5991,ND.0001,NaN,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN

In [64]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2016.09.18.c,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,16,Minor injury to thigh,N,13,NaN
1,2016.09.18.b,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,36,Lacerations to hands,N,11,NaN
2,2016.09.18.a,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,43,Lacerations to lower leg,N,10.7167,NaN
3,2016.09.17,9,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,M,NaN,Struck by fin on chest & leg,N,NaN,NaN
4,2016.09.15,9,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark

In [71]:
age = df['Age']
count2 = 0

for i in age: 
    try: 
        if len(i) > 2: 
            age[count2] = float('nan')
        elif isinstance(i, str): 
            age[count2] = float('nan')
        else: 
            age[count2] = int(i)
        
    except: 
        pass 
    count2 += 1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [90]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2016.09.18.c,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,16,Minor injury to thigh,N,13,NaN
1,2016.09.18.b,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,36,Lacerations to hands,N,11,NaN
2,2016.09.18.a,9,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,43,Lacerations to lower leg,N,10.7167,NaN
3,2016.09.17,9,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,M,NaN,Struck by fin on chest & leg,N,NaN,NaN
4,2016.09.15,9,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark

In [92]:
df['Fatal (Y/N)'].unique()

array(['N', 'Y', nan, 'UNKNOWN', ' N', 'F', 'N ', '#VALUE!', 'n'],
      dtype=object)

In [93]:
#Converting Fatal Column to 0 and 1


f = df['Fatal (Y/N)']
count3 = 0

for i in f: 
    try:
        if i == 'UNKNOWN': 
            f[count3] = float('nan')
        elif 'n' in i.lower() or i == 'F':
            f[count3] = 0 
        elif i == 'Y':
            f[count3] = 1 
        else: 
            f[count3] = float('nan')
    except: 
        pass 
    count3 += 1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

In [94]:
f.unique()

array([0, 1, nan], dtype=object)

In [95]:
f.mean()

0.2640353861857775

In [96]:
df['Date'].mean()

6.582345431333212

In [105]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time', 'Species '],
      dtype='object')

In [118]:
#renaming columns
df = df.rename(columns={'Sex ':'Sex', 'Species ':'Species'})

In [120]:
df['Sex'].unique()

array(['M', nan, 'F', 'M ', 'lli', 'N', '.'], dtype=object)

In [126]:
#Converting female 0 and male 1
s = df['Sex']
count4 = 0

for i in s: 
    try: 
        if 'm' in i.lower(): 
            s[count4] = 1
        elif 'f' in i.lower(): 
            s[count4] = 0  
        else: 
            s[count4] = float('nan')
    except: 
        pass 
    count4 += 1

In [128]:
print(s.mean(), s.std(), s.var(), s.unique())

0.8921062338620436 0.3102748086641702 0.09627045689158742 [1 nan 0]